name: ecommers_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  scroll_snap_list: ^0.9.1
  intl: ^0.19.0
  casa_vertical_stepper: ^0.0.5
  lottie: ^3.1.3
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.6
  image_picker: ^1.1.2
  shared_preferences: ^2.3.3
  provider: ^6.1.2
  convex_bottom_bar: ^3.2.0
  google_sign_in: ^7.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/vegitable/
    - assets/pesticide/
    - assets/vegetable/
    - assets/login/
    - assets/flower/
    - assets/images/
    - assets/images/aneet.png
    
